# coding:utf-8
import os

HEART_BEAT_SECONDS = 10  # 中心与其它服务之间的心跳时间

SERVICE_GATE = 9999  # 网关服务
SERVICE_PUB_SUB = 9998  # 发布订阅服务
SERVICE_WEB = 9996
SERVICE_SYSTEM = 1  # 系统服务
SERVICE_AUTH = 2  # 登录认证服务
SERVICE_MALL = 3  # 商城服务
SERVICE_CDPH = 8  # 常德跑胡
SERVICE_ZZMJ = 9  # 转转麻将
SERVICE_HZMJ = 10  # 红中麻将
SERVICE_SYMJ = 11  # 邵阳麻将
SERVICE_CSMJ = 12  # 长沙麻将
SERVICE_TIAN_ZHA = 13  # 天炸
SERVICE_KOU_BO = 14  # 抠僰
SERVICE_YXHZP = 15  # 攸县胡子牌
SERVICE_GHZ = 16  # 鬼胡子
SERVICE_BPH = 17  # 剥皮胡
SERVICE_SXH = 18  # 上下混
SERVICE_NIU_GUI = 19  # 牛鬼
SERVICE_GDMJ = 20  # 桂东麻将
SERVICE_PDK = 21  # 跑得快
SERVICE_DTZ = 22  # 打筒子
SERVICE_BCNN = 23  # 牛牛
SERVICE_ZHU_PO_JIU = 24  # 猪婆9
SERVICE_XTMJ = 25  # 湘潭麻将
SERVICE_YXPH = 26  # 攸县碰胡
SERVICE_510K = 27  # 510K
SERVICE_XTPH = 28  # 湘潭跑胡
SERVICE_SDH = 29  # 三打哈
SERVICE_NIUNIU = 30  # 冰城牛牛
SERVICE_EBG = 31  # 二八杠
SERVICE_SHUANG_KOU = 32  # 双扣
SERVICE_SHI_SAN_DAO = 33  # 十三道
SERVICE_YZCHZ = 34  # 永州扯胡子
SERVICE_CZPHZ = 35  # 郴州跑胡子
SERVICE_FENG_HUANG_HUA_SHUI = 36  # 凤凰划水
SERVICE_HENG_YANG_MO_MO = 37  # 衡阳摸摸
SERVICE_FENG_HUANG_HONG_ZHONG = 38  # 凤凰红中
SERVICE_ZLMZ = 39  # 捉老麻子
SERVICE_HUAI_HUA_QUAN_MING_TANG = 40  # 怀化全名堂
SERVICE_TUI_DAO_HU = 41  # 推倒胡
SERVICE_FANG_PAO_FA = 42  # 放炮罚
SERVICE_HAN_SHOU_PAO_HU = 43  # 汉寿跑胡子

SERVICE_ZJH = 47 # 诈金花

SERVICE_AHPF = 66 #安化跑胡子

USER_APPLY_JOIN_CLUB = 2
ADD_USER_TO_CLUB = 3
PASS_USER_JOIN_CLUB = 4
AUTO_ROOM_CHANGE = 5
CLUB_CREATE_ROOM = 6
USER_CHANGE_DOU = 9

USER_APPLY_JOIN_UNION = 12
ADD_USER_TO_UNION = 13
PASS_JOIN_GROUP = 14

PLAYER_TABLE_REMOVE = 71
UNION_SUBFLOOR_REMOVE_NOTICE = 79 #联盟游戏删除通知联盟所有的玩家
GAME_PLAY_CONFIG_CHANGE = 90
UNION_GAME_PLAY_CONFIG_CHANGE = 91              # 联盟游戏玩法修改
DEBUG_PLAYERS_INFO = 96
DEBUG_CARDS_INFO = 97

REASON_SEND = 1  # 玩家转账
REASON_RECEIVE = 2  # 接收到转账
REASON_SYSTEM_ADD = 3  # 系统添加
REASON_SYSTEM_SUB = 4  # 系统减少
REASON_BIND_SUCCESS = 5  # 绑定成功
REASON_INVITE_SUCCESS = 6  # 邀请成功
REASON_RE_INVITE_SUCCESS = 7  # 二次邀请成功
REASON_CREATE_ROOM_SUCCESS = 8  # 第一次创建房间成功
REASON_CREATE_ROOM_SUB = 10  # 开房扣除
REASON_LOTTERY = 15  # 开房红包
REASON_BIND = 16  # 绑定赠送
REASON_IAP = 19  # IAP 充值钻石
REASON_SHARE = 20  # 分享朋友圈赠送
REASON_EXCHANGE = 21  # 活动兑换

REASON_CLUB_ADD = 25  # 俱乐部馆主增加
REASON_CLUB_SUB = 26  # 俱乐部馆主扣除
REASON_GAME_ADD = 27  # 游戏增加
REASON_GAME_SUB = 28  # 游戏扣除
REASON_GAME_LIMIT_SUB = 29  # 游戏抽成

REASON_GAME_SCORE_BUY_ITEM = 33  # 购买积分物品

REASON_UNION_ADD = 1  # 联盟增加
REASON_UNION_SUB = 0  # 联盟减少
REASON_UNION_TRANSFER = 2  # 联盟转移

TYPE_LOGIN = 1  # 活跃用户表类型(登录)
TYPE_REG = 2  # 活跃用户表类型(注册)

PAY_TYPE_CREATOR = 0
PAY_TYPE_AA = 1
PAY_TYPE_WINNER = 2

DIAMOND_ROOM = 0
MATCH_ROOM = 1

CALC_DIAMOND_WITH_PLAYER_NUM = [SERVICE_FENG_HUANG_HUA_SHUI]

# System Running Path.
BASE_PATH = os.path.dirname(os.path.realpath(__file__)) + '/../'

# 日志文件写入路径
LOG_PATH = BASE_PATH + 'output/logs/'

BASE_API_URL = ''
BASE_API_TEST_URL = ''
GET_CODE_URL = BASE_API_URL + ''
GET_CODE_LIST_URL = BASE_API_URL + ''
KEY = ''

if __name__ == "__main__":
    print(BASE_PATH, LOG_PATH)
